# Generated by Django 5.0.3 on 2024-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0004_remove_politic_phone_politic_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politic',
            name='foto',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
