# Generated by Django 5.0.3 on 2024-03-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0005_politic_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politic',
            name='foto',
        ),
    ]
