# Generated by Django 5.0.3 on 2024-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0006_remove_politic_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitpolitic',
            name='members',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reunio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reunio',
            name='members',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partitpolitic',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
