# Generated by Django 5.0.3 on 2024-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0007_partitpolitic_members_reunio_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunio',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
