# Generated by Django 5.0.3 on 2024-03-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0008_reunio_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunio',
            name='hours',
        ),
        migrations.AddField(
            model_name='reunio',
            name='hour',
            field=models.IntegerField(max_length=24, null=True),
        ),
    ]
