# Generated by Django 5.0.3 on 2024-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0009_remove_reunio_hours_reunio_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunio',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
