# Generated by Django 5.0.3 on 2024-03-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0010_alter_reunio_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunio',
            name='hour',
        ),
    ]
