# Generated by Django 5.0.3 on 2024-03-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelManagement', '0011_remove_reunio_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunio',
            name='politic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelManagement.politic'),
        ),
    ]
